name: NoPorts Example

on:
  workflow_dispatch:

jobs:
  noports-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NoPorts and Authentication
        uses: atsign-foundation/noports-action@464b931232f49cd302ecf5eb913cfe2c778fbd6e # v1.0.0
        with:
          atsign: '@stepcaprod'
          atkeys-secret: ${{ secrets.ATKEYS_STEPCAPROD }}

      - name: Establish a NoPorts tunnel
        run: |
          # The action placed the keys in the default ~/.atsign/keys/ location
          nohup npt -f stepcaprod -t cookingthelemon -r rv_am -d stepcaprod \
            -l 3443 -p 3443 --rh 127.0.0.1 --lh 127.0.0.1 -T 0 \
            > npt.log 2> npt.err < /dev/null &
          tail -f npt.err | grep -m 1 "npt is listening"

      # Ensure runner trusts our CA
      - name: Add Custom CA to Runner Trust Store
        run: |
          echo "${{ vars.PRODCA }}" | sudo tee /usr/local/share/ca-certificates/stepcaprod.crt > /dev/null
          sudo update-ca-certificates

      - name: Test connection to CA
        run: |
          curl https://ca.atsign.org:3443/acme/acme/directory
